# Generated by Django 4.1.1 on 2022-09-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.IntegerField(blank=True, verbose_name='Количество'),
        ),
    ]
