# Generated by Django 4.1.1 on 2022-09-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loop', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
